name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.*"
  pull_request:
    paths:
      - ".github/workflows/release.yml"
      - ".goreleaser.yml"

permissions:
  # required for upload archives as GitHub Releases
  contents: write
  # required for push Docker images
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DESCRIPTION: "Generate documentation from Custom Actions and Reusable Workflows."

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
